item {
    name: "Aligator Crack",
    id: 1,
    display_name: "Aligator Crack"
}
item {
    name: "Block Crack",
    id: 2,
    display_name: "Block Crack"
}
item {
    name: "Lane Longitudinal Crack",
    id: 3,
    display_name: "Lane Longitudinal Crack"
}
item {
    name: "Longitudinal Crack",
    id: 4,
    display_name: "Longitudinal Crack"
}
item {
    name: "Reflective Crack",
    id: 5,
    display_name: "Reflective Crack"
}
item {
    name: "Sealed Longitudinal Crack",
    id: 6,
    display_name: "Sealed Longitudinal Crack"
}
item {
    name: "Sealed Reflective Crack",
    id: 7,
    display_name: "Sealed Reflective Crack"
}
item {
    name: "Sealed Transvers Cracks",
    id: 8,
    display_name: "Sealed Transvers Cracks"
}
item {
    name: "Transvers Crack",
    id: 9,
    display_name: "Transvers Crack"
}
item {
    name: "pothole",
    id: 10,
    display_name: "pothole"
}
