# -*- coding: utf-8 -*-
"""Extracting image in Google street view api revision.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aW2a5PY77akEvJXviV98zjKvHh0C0Fh5
"""

pip install google_streetview

import google_streetview.api
import json

















import requests
import matplotlib.image as mpimg
def detect(location, api_key):
  pic_base = 'https://maps.googleapis.com/maps/api/streetview?'
  pic_params = {
	  'size': '600x300', # max 640x640 pixels
	  'location': location,
	  'key': api_key,

  }
  pic_response = requests.get(pic_base, params=pic_params)
  global number = number + 1
  with open('result' + number + '.jpg', 'wb') as file:
    file.write(pic_response.content)
  # remember to close the response connection to the API
  pic_response.close()
  img=mpimg.imread('result' + number + '.jpg')
  return img